#!/usr/bin/env python3
# seLe4n  - A Lean Microkernel
# Copyright (C) 2026  Adam Hall
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions. See: https://github.com/hatter6822/seLe4n/blob/main/LICENSE
"""Generate `AGENTS.md`, the pointer file that sends other agents to `CLAUDE.md`.

`AGENTS.md` states no rules of its own.  It is a fixed template plus the list
of `CLAUDE.md`'s top-level (`## `) headings, so the whole file is a function of
`CLAUDE.md` and is checked byte for byte: any added prose, a dropped line or a
stale heading list fails, not only a stale list.

    python3 scripts/generate_agents_md.py              # rewrite AGENTS.md
    python3 scripts/generate_agents_md.py --check      # exit 1 if it differs
    python3 scripts/generate_agents_md.py --self-test  # the heading reader

A heading is read as CommonMark reads an ATX heading, from
`markdown_prose_view.prose_view`, the fence reader the plan gates share, so an
example `## ` line inside any fence (backtick or tilde, indented or not) is not
a section, and a prose line opening with inline code hides nothing.  A setext
heading (a line underlined with `=` or `-`) is refused rather than silently
left out of the list.

`--check` is what `scripts/test_docs_sync.sh` runs.  It also requires that
`AGENTS.md` is a regular file, both in the git index (mode 100644) and in the
working tree, because a symlink to `CLAUDE.md` is flattened to a one-line file
by a `core.symlinks=false` checkout.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from markdown_prose_view import prose_view  # noqa: E402  (needs the path insert above)

REPO = Path(__file__).resolve().parent.parent
CLAUDE = REPO / "CLAUDE.md"
AGENTS = REPO / "AGENTS.md"

TEMPLATE = """\
# AGENTS.md — the project rules are in CLAUDE.md

<!-- Generated by scripts/generate_agents_md.py from CLAUDE.md's headings.
     Do not edit by hand; scripts/test_docs_sync.sh checks it byte for byte. -->

**All project rules for this repository live in [`CLAUDE.md`](CLAUDE.md).
Read that file in full before doing any work here** — building, editing,
reviewing, or answering questions about the code. This file states no rules of
its own: an agent that reads only this file has read none of them.

`CLAUDE.md` is named for the tool that auto-loads it; it binds every
contributor, human or agent. Edit `CLAUDE.md` only, then run
`python3 scripts/generate_agents_md.py` to refresh the section list below.

## Sections of CLAUDE.md

{sections}
"""


# An ATX heading: up to three columns of indent, the opening `#` run, and an
# optional closing `#` run (CommonMark 4.2).
ATX_HEADING = re.compile(r"^ {0,3}(#{1,6})(?:[ \t]+(.*?))?(?:[ \t]+#+)?[ \t]*$")
# A setext underline: up to three columns of indent and a run of `=` or `-`.
SETEXT_UNDERLINE = re.compile(r"^ {0,3}(?:=+|-+)[ \t]*$")


def headings(text: str) -> list[str]:
    """`CLAUDE.md`'s level-2 headings, in order, outside fenced code blocks."""
    out: list[str] = []
    previous = ""
    for line in prose_view(text).splitlines():
        atx = ATX_HEADING.match(line)
        if atx and len(atx.group(1)) == 2:
            out.append((atx.group(2) or "").strip())
        elif (SETEXT_UNDERLINE.match(line) and previous.strip()
              and not ATX_HEADING.match(previous)):
            # `Title` over `---` is a level-2 heading in CommonMark; over a list
            # item or a table it may not be.  Refuse rather than guess.
            raise SystemExit(f"FAIL: CLAUDE.md underlines {previous.strip()!r} "
                             "(a setext heading); write it as an ATX `## ` heading")
        previous = line
    return out


def render(claude_text: str) -> str:
    hs = headings(claude_text)
    if not hs:
        # Fail closed: an empty list would render a pointer to nothing and
        # every comparison against it would be vacuous.
        raise SystemExit("FAIL: CLAUDE.md has no top-level (## ) headings")
    return TEMPLATE.format(sections="\n".join(f"- {h}" for h in hs))


def regular_file_errors() -> list[str]:
    errors: list[str] = []
    entry = subprocess.run(["git", "ls-files", "-s", "--", "AGENTS.md"], cwd=REPO,
                           capture_output=True, text=True, check=True).stdout
    mode = entry.split(" ", 1)[0] if entry else "absent"
    if mode != "100644":
        errors.append(f"AGENTS.md must be a regular file in the git index "
                      f"(mode {mode}, want 100644)")
    if AGENTS.is_symlink() or not AGENTS.is_file():
        errors.append("the working-tree AGENTS.md must be a regular file, "
                      "not a symlink or missing")
    return errors


def _self_test() -> int:
    """Keep each `## Example` token in place and move it inside or outside a fence."""
    cases = [
        ("a tilde fence hides its `## Example`",
         "## Real\n~~~\n## Example\n~~~\n## After\n", ["Real", "After"]),
        ("an indented fence hides its `## Example`",
         "## Real\n   ```\n## Example\n   ```\n## After\n", ["Real", "After"]),
        ("a longer closer, not a shorter run, ends the fence",
         "## Real\n````\n```\n## Example\n`````\n## After\n", ["Real", "After"]),
        ("a prose line opening with inline code hides no later heading",
         "## Real\n``` `x` ``` opens a sentence.\n## After\n", ["Real", "After"]),
        ("an ATX heading indented three columns, or closed with `#`, is read",
         "   ## Indented\n## Closed ##\n### Deeper\n", ["Indented", "Closed"]),
    ]
    failed = 0
    for name, text, want in cases:
        got = headings(text)
        ok = got == want
        failed += not ok
        print(f"  {'PASS' if ok else 'FAIL'}: {name}" + ("" if ok else f" -- got {got}"))
    try:
        headings("## Real\nA setext title\n---\n")
        print("  FAIL: a setext heading is refused -- it was accepted")
        failed += 1
    except SystemExit as refused:
        ok = "setext heading" in str(refused)
        failed += not ok
        print(f"  {'PASS' if ok else 'FAIL'}: a setext heading is refused")
    if failed:
        print(f"SELF-TEST FAILED: {failed} case(s)")
        return 1
    print(f"generate_agents_md self-test: {len(cases) + 1} cases, all correct.")
    return 0


def main(argv: list[str]) -> int:
    if argv == ["--self-test"]:
        return _self_test()
    check = "--check" in argv
    want = render(CLAUDE.read_text(encoding="utf-8"))
    if not check:
        if AGENTS.is_symlink():
            AGENTS.unlink()
        AGENTS.write_text(want, encoding="utf-8")
        print("wrote AGENTS.md")
        return 0
    errors = regular_file_errors()
    if not errors:
        have = AGENTS.read_text(encoding="utf-8")
        if have != want:
            errors.append("AGENTS.md differs from what scripts/generate_agents_md.py "
                          "renders from CLAUDE.md; run it to regenerate (the file "
                          "is generated and states no rules of its own)")
            hl, wl = have.splitlines(), want.splitlines()
            for i in range(max(len(hl), len(wl))):
                h = hl[i] if i < len(hl) else "<missing>"
                w = wl[i] if i < len(wl) else "<missing>"
                if h != w:
                    errors.append(f"first difference at line {i + 1}: "
                                  f"have {h!r}, want {w!r}")
                    break
    for e in errors:
        print(f"FAIL: {e}", file=sys.stderr)
    if errors:
        return 1
    print("PASS: AGENTS.md is the generated pointer to CLAUDE.md, byte for byte.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
