#!/usr/bin/env python3
# seLe4n  - A Lean Microkernel
# Copyright (C) 2026  Adam Hall
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions. See: https://github.com/hatter6822/seLe4n/blob/main/LICENSE
"""Generate `AGENTS.md`, the pointer file that sends other agents to `CLAUDE.md`.

`AGENTS.md` states no rules of its own.  It is a fixed template plus the list
of `CLAUDE.md`'s top-level (`## `) headings, so the whole file is a function of
`CLAUDE.md` and is checked byte for byte: any added prose, a dropped line or a
stale heading list fails, not only a stale list.

    python3 scripts/generate_agents_md.py           # rewrite AGENTS.md
    python3 scripts/generate_agents_md.py --check   # exit 1 if it differs

`--check` is what `scripts/test_docs_sync.sh` runs.  It also requires that
`AGENTS.md` is a regular file, both in the git index (mode 100644) and in the
working tree, because a symlink to `CLAUDE.md` is flattened to a one-line file
by a `core.symlinks=false` checkout.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLAUDE = REPO / "CLAUDE.md"
AGENTS = REPO / "AGENTS.md"

TEMPLATE = """\
# AGENTS.md — the project rules are in CLAUDE.md

<!-- Generated by scripts/generate_agents_md.py from CLAUDE.md's headings.
     Do not edit by hand; scripts/test_docs_sync.sh checks it byte for byte. -->

**All project rules for this repository live in [`CLAUDE.md`](CLAUDE.md).
Read that file in full before doing any work here** — building, editing,
reviewing, or answering questions about the code. This file states no rules of
its own: an agent that reads only this file has read none of them.

`CLAUDE.md` is named for the tool that auto-loads it; it binds every
contributor, human or agent. Edit `CLAUDE.md` only, then run
`python3 scripts/generate_agents_md.py` to refresh the section list below.

## Sections of CLAUDE.md

{sections}
"""


def headings(text: str) -> list[str]:
    """`CLAUDE.md`'s `## ` headings, in order, outside fenced code blocks."""
    out: list[str] = []
    fenced = False
    for line in text.splitlines():
        if line.startswith("```"):
            fenced = not fenced
        elif not fenced and line.startswith("## "):
            out.append(line[3:].strip())
    return out


def render(claude_text: str) -> str:
    hs = headings(claude_text)
    if not hs:
        # Fail closed: an empty list would render a pointer to nothing and
        # every comparison against it would be vacuous.
        raise SystemExit("FAIL: CLAUDE.md has no top-level (## ) headings")
    return TEMPLATE.format(sections="\n".join(f"- {h}" for h in hs))


def regular_file_errors() -> list[str]:
    errors: list[str] = []
    entry = subprocess.run(["git", "ls-files", "-s", "--", "AGENTS.md"], cwd=REPO,
                           capture_output=True, text=True, check=True).stdout
    mode = entry.split(" ", 1)[0] if entry else "absent"
    if mode != "100644":
        errors.append(f"AGENTS.md must be a regular file in the git index "
                      f"(mode {mode}, want 100644)")
    if AGENTS.is_symlink() or not AGENTS.is_file():
        errors.append("the working-tree AGENTS.md must be a regular file, "
                      "not a symlink or missing")
    return errors


def main(argv: list[str]) -> int:
    check = "--check" in argv
    want = render(CLAUDE.read_text(encoding="utf-8"))
    if not check:
        if AGENTS.is_symlink():
            AGENTS.unlink()
        AGENTS.write_text(want, encoding="utf-8")
        print("wrote AGENTS.md")
        return 0
    errors = regular_file_errors()
    if not errors:
        have = AGENTS.read_text(encoding="utf-8")
        if have != want:
            errors.append("AGENTS.md differs from what scripts/generate_agents_md.py "
                          "renders from CLAUDE.md; run it to regenerate (the file "
                          "is generated and states no rules of its own)")
            hl, wl = have.splitlines(), want.splitlines()
            for i in range(max(len(hl), len(wl))):
                h = hl[i] if i < len(hl) else "<missing>"
                w = wl[i] if i < len(wl) else "<missing>"
                if h != w:
                    errors.append(f"first difference at line {i + 1}: "
                                  f"have {h!r}, want {w!r}")
                    break
    for e in errors:
        print(f"FAIL: {e}", file=sys.stderr)
    if errors:
        return 1
    print("PASS: AGENTS.md is the generated pointer to CLAUDE.md, byte for byte.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
