#!/usr/bin/env python3
"""Generate canonical GitBook navigation pages from a single manifest.

WS-B8 objective: keep handbook navigation deterministic and easy to sync.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "docs/gitbook/navigation_manifest.json"
README_PATH = REPO_ROOT / "docs/gitbook/README.md"
SUMMARY_PATH = REPO_ROOT / "docs/gitbook/SUMMARY.md"


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def format_readme(manifest: dict) -> str:
    lines: list[str] = []
    lines.append("# seLe4n Handbook")
    lines.append("")
    lines.append("<!-- AUTO-GENERATED by scripts/generate_doc_navigation.py; edit docs/gitbook/navigation_manifest.json -->")
    lines.append("")
    lines.append(manifest["description"])
    lines.append("")
    lines.append("## Current project state")
    for bullet in manifest["current_state_bullets"]:
        lines.append(f"- {bullet}")
    lines.append("")
    lines.append("Normative scope and acceptance source:")
    lines.append("[`docs/SEL4_SPEC.md`](../SEL4_SPEC.md).")
    lines.append("")
    lines.append("## Recommended reading path (new developers)")
    lines.append("")
    for index, item in enumerate(manifest["recommended_reading"], start=1):
        lines.append(f"{index}. [{item['title']}]({item['path']})")
    lines.append("")
    lines.append("## Where to find current workstream detail")
    lines.append("")
    lines.append("- Canonical execution matrix:")
    lines.append("  [`docs/audits/COMPREHENSIVE_AUDIT_2026_02_WORKSTREAM_PLAN.md`](../audits/COMPREHENSIVE_AUDIT_2026_02_WORKSTREAM_PLAN.md)")
    lines.append("- GitBook planning chapter:")
    lines.append("  [Comprehensive Audit 2026 Workstream Planning](24-comprehensive-audit-2026-workstream-planning.md)")
    lines.append("")
    lines.append("## Historical slice archive")
    lines.append("")
    lines.append("M7, M6, M5, and M4 chapters are retained as historical references and should not be interpreted as active execution status.")
    lines.append("")
    return "\n".join(lines)


def format_summary(manifest: dict) -> str:
    lines: list[str] = []
    lines.append("# Summary")
    lines.append("")
    lines.append("<!-- AUTO-GENERATED by scripts/generate_doc_navigation.py; edit docs/gitbook/navigation_manifest.json -->")
    lines.append("")
    lines.append("- [seLe4n Handbook](README.md)")
    lines.append("")
    for section in manifest["summary_sections"]:
        lines.append(f"## {section['section']}")
        lines.append("")
        for page in section["pages"]:
            lines.append(f"- [{page['title']}]({page['path']})")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    manifest = load_manifest()
    README_PATH.write_text(format_readme(manifest), encoding="utf-8")
    SUMMARY_PATH.write_text(format_summary(manifest), encoding="utf-8")
    print(f"generated {README_PATH.relative_to(REPO_ROOT)}")
    print(f"generated {SUMMARY_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
