#!/usr/bin/env bash
# U3-J: Rust ABI conformance test runner.
#
# Runs the full Rust workspace test suite and verifies that all
# conformance test vectors pass. Optionally generates test vector
# fixture output for cross-validation against the Lean model.
#
# Usage:
#   ./scripts/test_rust_conformance.sh          # Run tests
#   ./scripts/test_rust_conformance.sh --dump    # Run + dump fixture vectors

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RUST_DIR="$ROOT_DIR/rust"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo "=== U3-J: Rust ABI Conformance Test Suite ==="
echo ""

# Step 1: Compile-time checks (layout assertions, deny(unsafe_code))
echo -e "${YELLOW}[1/4]${NC} Checking workspace compilation..."
cd "$RUST_DIR"
if ! cargo check --workspace 2>&1; then
    echo -e "${RED}FAIL${NC}: Workspace compilation failed"
    exit 1
fi
echo -e "${GREEN}  ✓${NC} Workspace compiles cleanly"

# Step 2: Run all unit tests
echo -e "${YELLOW}[2/4]${NC} Running unit tests..."
if ! cargo test --workspace 2>&1; then
    echo -e "${RED}FAIL${NC}: Unit tests failed"
    exit 1
fi
echo -e "${GREEN}  ✓${NC} All unit tests pass"

# Step 3: Run conformance tests specifically (filter by test name prefix)
echo -e "${YELLOW}[3/4]${NC} Running conformance tests..."
XVAL_COUNT=$(cargo test --package sele4n-abi --test conformance 2>&1 | grep -c "^test .* ok$" || true)
echo -e "${GREEN}  ✓${NC} $XVAL_COUNT conformance tests pass"

# Step 4: Check for unsafe code outside trap.rs
echo -e "${YELLOW}[4/4]${NC} Verifying unsafe code containment..."
UNSAFE_FILES=$(grep -rl "unsafe" "$RUST_DIR" --include="*.rs" \
    | grep -v "target/" \
    | grep -v "trap.rs" \
    | grep -v "deny(unsafe_code)" \
    | grep -v "#\[allow(unsafe_code)\]" \
    || true)

if [ -n "$UNSAFE_FILES" ]; then
    echo -e "${YELLOW}  ⚠${NC} Found 'unsafe' keyword in files (verify these are deny/allow annotations):"
    echo "$UNSAFE_FILES" | head -10
else
    echo -e "${GREEN}  ✓${NC} Zero unsafe code outside trap.rs"
fi

# Optional: dump test vectors for Lean cross-validation
if [[ "${1:-}" == "--dump" ]]; then
    echo ""
    echo "=== Test Vector Fixture Dump ==="
    echo "# Generated by test_rust_conformance.sh --dump"
    echo "# Format: VECTOR_ID | INPUT | EXPECTED_OUTPUT"
    echo "#"
    echo "# MessageInfo encode/decode vectors"
    echo "MI-001 | new(0, 0, 0)       | encode=0x0000000000000000"
    echo "MI-002 | new(120, 3, 0)     | encode=0x00000000000001F8"
    echo "MI-003 | new(42, 2, 0x1234) | encode=0x000000000024692A"
    echo "MI-004 | new(0, 0, MAX)     | reject=InvalidMessageInfo (label >= 2^55)"
    echo "#"
    echo "# AccessRights vectors"
    echo "AR-001 | try_from(0x00) | ok(EMPTY)"
    echo "AR-002 | try_from(0x1F) | ok(ALL)"
    echo "AR-003 | try_from(0x20) | err(AccessRightsError)"
    echo "AR-004 | try_from(0xFF) | err(AccessRightsError)"
    echo "#"
    echo "# KernelError vectors"
    echo "KE-001 | from_u32(0)  | Some(InvalidCapability)"
    echo "KE-002 | from_u32(37) | Some(AllocationMisaligned)"
    echo "KE-003 | from_u32(38) | None"
fi

echo ""
echo -e "${GREEN}=== All conformance checks passed ===${NC}"
